// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnuiaunbrnzyafrihkei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudWlhdW5icm56eWFmcmloa2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMzgxNDcsImV4cCI6MjA0OTkxNDE0N30.3uBmPSC_NO4eqGFpG6T8xGe8Pc7OcWW_Qrm0DYcLoYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);